### PR TITLE
bug removed

### PR DESCRIPTION
**Pull request by gigwe1**
Please review and merge. bug removed

### CODE REVIEW

**Review by princeochiss — COMMENTED** [review]
Sr Engr. GG I have reviewed and satisfy

**Comment by princeochiss** [comment]
This is fixed

**Review by princeochiss — APPROVED** [review]

**Review by gigwe1 — COMMENTED** [review]
Great job

**Review by IgweTech — COMMENTED** [review]
This is good, you may proceed with the package.

**Comment by princeochiss** [comment]
With God we done hammer

**Pull request merged**
